### ISSUE TITLE
create a default chat on start and auto add friends to default chat

### ISSUE THREAD

**Issue by Scratch-net** [JFreegman/ToxBot#1]
Hi there, thank you for such an awesome tool. I have two suggestions to make it more robust
1) Create a default room on start, so that it could be fully functional in case of reboot.
2) Automatically invite friends to a default room (option) when they become online, so that if they got network outage they wouldn't have to type "invite" again.

I'd do that myself, but I'm more of a c# guy. Thanks

**Comment by JFreegman** [comment]
1. if you reboot then you're going to need someone else to invite you back to the original room; you probably don't want to start a new one.
2. This would be annoying for contacts who don't want to join the groupchat. Usually the majority of groupbot's online friends aren't in the groupchat.

I appreciate the suggestions though, I'm always looking for ways to improve it.
