### ISSUE TITLE
Creating a new group

### ISSUE THREAD

**Issue by morpheusbeing** [JFreegman/ToxBot#2]
I am a bit confused about the process to create a new group that has a number other than 0 so it does not clash with other groups - or do I not have to do that - just leave group number at 0. Also it would be good, for master commands to be embedded in the code ie set command to ? like in lambdabot followed by characters or words to carry out command.

**Comment by morpheusbeing** [comment]
I have created default group 0, but when issue invite 0, get message group does not exist

**Comment by JFreegman** [comment]
@morpheusbeing you don't need to specify the group number when you create it. Just use the `info` command.

The bot will delete empty groups once per minute due to allowing anyone to create groups (probably a bad feature in hindsight). just create it again and join before it gets deleted. I'm not putting anymore time into developing ToxBot because it will become deprecated when the new tox groups are ready.

**Comment by morpheusbeing** [comment]
didn't realise was going to become depreciated.

On 30/03/15 13:05, JFreegman wrote:

> @morpheusbeing https://github.com/morpheusbeing you don't need to
> specify the group number when you create it.
> 
> The bot will delete empty groups once per minute due to allowing
> anyone to create groups (probably a bad feature in hindsight). just
> create it again and join before it gets deleted. I'm not putting
> anymore time into developing ToxBot because it will become deprecated
> when the new tox groups are ready.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JFreegman/ToxBot/issues/2#issuecomment-87525198.

## 

---

**Comment by morpheusbeing** [comment]
Ah ha, I now know the problem - is my satellite delay of signals. Thanks
for assistance.

On 30/03/15 13:05, JFreegman wrote:

> @morpheusbeing https://github.com/morpheusbeing you don't need to
> specify the group number when you create it.
> 
> The bot will delete empty groups once per minute due to allowing
> anyone to create groups (probably a bad feature in hindsight). just
> create it again and join before it gets deleted. I'm not putting
> anymore time into developing ToxBot because it will become deprecated
> when the new tox groups are ready.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JFreegman/ToxBot/issues/2#issuecomment-87525198.

## 

---
