### ISSUE TITLE
[bug] "Error: Invalid Tox ID" with 64 chars ToxID

### ISSUE THREAD

**Issue by tetraf** [JFreegman/ToxBot#6]
I get "Error: Invalid Tox ID" when I try to add a masterkey with a 64 chars ToxID (which is valid) and "ID added to masterkeys list" for a 76 chars one.
If I try to add the 64 chars ToxID to masterkeys file and restart toxbot it doesn't connect to Tox network without error message.

**Comment by JFreegman** [comment]
A Tox ID is 76 characters long. The first 64 characters are just the public key portion of the ID and will not work alone. A full Tox ID looks like this:
`[ [Public Key (32 bytes)] [nospam (4 bytes)] [checksum (2 bytes)] ]`

The masterkeys file doesn't affect how it connects.

**Comment by tetraf** [comment]
I know but there are some clients (old ones perhaps) which give 64 chars ToxID. In my roster I have some friends with a 64 chars ToxID, and I can talk to them.

**Comment by JFreegman** [comment]
They give you the public key so that you can verify who your friends are. Those can't be used in place of Tox ID's. You'll have to ask them for their full ID if you want to add them to the masterkeys file.

**Comment by tetraf** [comment]
Yep, I don't like to annoy users for things that some config/dev could solve. Nevermind, I'll cope.

**Comment by JFreegman** [comment]
It's not really something that I could solve because there's no API call that gets the full 76 character ID of a friend.
